// @ts-ignore

const variables = {
  "@font-thin": "100",
  "@font-extra-light": "200",
  "@font-light": "300",
  "@font-regular": "400",
  "@font-medium": "500",
  "@font-semi-bold": "600",
  "@font-bold": "700",
  "@font-extra-bold": "800",
  "@font-black": "900",
  "@font-family" : "'Catamaran', sans-serif",
  "@text-color" : "#AEAEAE",
  "@primary-color" : "#0053FA",
  "@light-color" : "#989CA8",
  "@lighter-color" : "#B5B9C5",
  "@default-color" : "#0d1b2a",
  "@error-color": "#F0455A",
  "@light-red": "#FF5F5F",
  "@light-orange": "#FF7960",
  "@red": "#F06879",
  "@dark-red": "#F0455A",
  "@light-gray": "#F5F6FA",
  "@light-green": "#5DBE42",
  "@font-size-base": "16px",
  "@border-radius-base" : "2px",
  "@border-color-base": "@primary-color",
  "@btn-primary-bg" : "@primary-color",
  "@btn-height-base" : "34px",
  "@label-required-color" : "#8a8a8a",
  "@label-color": "#8a8a8a",
  "@input-placeholder-color": "#c0c0c0",
  "@layout-header-background" : "#fff",
  "@wide-screen-down": "~'(max-width: 1199px)'",
  "@desktop-down": "~'(max-width: 991px)'",
  "@tablet-down": "~'(max-width: 767px)'",
  "@phone-down": "~'(max-width: 480px)'",
  "@small-phone-down": "~'(max-width: 320px)'",
  "@footer-bar-height": "55px",
  "@header-height": "64px",
};

module.exports = variables;
